name: SeleniumBase Browser Troubleshooting

on:
  # Allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  troubleshoot-browser:
    runs-on: ubuntu-latest # GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chromium Browser
        # SeleniumBase needs a browser. Chromium is a good choice for headless environments.
        # This command installs the snap version of Chromium which is common on Ubuntu.
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3 version available

      - name: Install Python dependencies
        run: |
          pip install seleniumbase requests # requests is included for general utility, though not strictly needed by this specific troubleshoot script

      - name: Run Browser Troubleshooting Script
        run: |
          python browser_troubleshoot.py

      - name: Upload Troubleshooting Results
        # This step uploads the results file as a workflow artifact,
        # which you can download from the GitHub Actions run summary page.
        uses: actions/upload-artifact@v4
        with:
          name: browser-troubleshoot-results
          path: browser_troubleshoot_results.txt
