name: Playwright DNB Scraper Troubleshooting (Finalized - Firefox)

on:
  # Allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  troubleshoot-scraper:
    runs-on: ubuntu-latest # GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WireGuard tools and resolvconf
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools resolvconf

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3 version available

      - name: Install Python dependencies
        run: |
          pip install playwright beautifulsoup4 requests

      - name: Install Playwright browsers
        # This step is crucial for Playwright to have the browser binaries
        run: |
          playwright install firefox

      - name: Run DNB Scraper Troubleshooting Script
        run: |
          python dnb_playwright_troubleshoot.py

      - name: Upload Troubleshooting Results
        uses: actions/upload-artifact@v4
        with:
          name: dnb-playwright-troubleshoot-results
          path: dnb_playwright_troubleshoot_results.txt

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: dnb-playwright-troubleshoot-screenshots
          path: playwright_troubleshoot_screenshots/
          if-no-files-found: ignore

      - name: Upload HTML Dumps
        uses: actions/upload-artifact@v4
        with:
          name: dnb-playwright-troubleshoot-html-dumps
          path: playwright_troubleshoot_html_dumps/
          if-no-files-found: ignore
