name: DNB Scraper with WireGuard & SeleniumBase

on:
  # Allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest # GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WireGuard tools and resolvconf
        # WireGuard tools (wg-quick) and resolvconf (for DNS management) are essential.
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools resolvconf

      - name: Install Chrome/Chromium for SeleniumBase
        # SeleniumBase needs a browser. Chromium is a good choice for headless environments.
        run: |
          sudo apt-get install -y chromium-browser

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3 version available

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4 dnspython seleniumbase

      - name: Run DNB Scraper script
        # The Python script will handle calling wg-quick with sudo and SeleniumBase operations
        run: |
          python linscr.py

      - name: Upload Scraper results
        # This step uploads the results file as a workflow artifact,
        # which you can download from the GitHub Actions run summary page.
        uses: actions/upload-artifact@v4
        with:
          name: dnb-scraper-results
          path: scraper_results.txt
